## STAGE1 of the gitlab-ci yml file development

stages:
# this governs the order that the stages will be run
  - build
  - push
  
build:
  image: docker:latest
  # this is a docker image that has the docker client baked into it. Used in CI/CD to build docker images
  # from a container
  stage: build
  # name of the stage for reference in the pipeline
  services:
    - docker:dind
    # docker in docker service
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    # this will run before main script below. Login using the gitlab credentials that we added to gitlab project
  script:
    - cd source_files/weatherapp/auth
    #- cd auth
    # first go into the auth directory source code for the authentication microservice.
    - docker build -t $CI_REGISTRY_USER/weatherapp-auth . --no-cache
    # no tag needed. We are just validating that docker can build the image from the auth source code.

    - cd ../UI
    - docker build -t $CI_REGISTRY_USER/weatherapp-ui .

    - cd ../weather
    - docker build -t $CI_REGISTRY_USER/weatherapp-weather .
  rules: 
    - if: '$CI_COMMIT_TAG == null'
    # run this only if no commit tag present
    # this will be run for all branches if no tag present

push:
#  If the image has a tag we do not need to run this again. Skip build and push and jump
# to stage called promote
  image: docker:latest
  stage: push
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
  # need to tag them because these images are pushed to docker hub
  # CI_COMMIT_SHA has a hash of the commit.
    #- cd auth
    - cd source_files/weatherapp/auth
    - docker build -t $CI_REGISTRY_USER/weatherapp-auth:$CI_COMMIT_SHA . --no-cache
    - docker push $CI_REGISTRY_USER/weatherapp-auth:$CI_COMMIT_SHA
    - cd ../UI
    - docker build -t $CI_REGISTRY_USER/weatherapp-ui:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_USER/weatherapp-ui:$CI_COMMIT_SHA
    - cd ../weather
    - docker build -t $CI_REGISTRY_USER/weatherapp-weather:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_USER/weatherapp-weather:$CI_COMMIT_SHA
  only:
    - main
    # only push the tagged image if on main branch.
    # we do not want to push all branches to docker hub